### ISSUE TITLE
Optitype error with gzipped fastqs

### ISSUE THREAD

**Issue by alvinwt** [FRED-2/OptiType#20]
Hi @andras86, 

I realized that razers3.4 has issues with gzipped fastqs due to seqan mentioned in [#987](https://github.com/seqan/seqan/issues/987). Is there other alignments that I can use in place of razers for optitype? It seems like razers3 is not maintained anymore.

**Comment by andras86** [comment]
Hi Alvin,

Yes, we're aware and we'll switch to Yara (developed by the same guy) soon. You'll need a small workaround then: you can feed OT the all-mapped bam files instead of the fastq files. So index hla_reference_(dna|rna).fasta first with yara_indexer. Then use the following call:

`yara_mapper -e 3 -f bam -u -os /path/to/ref path/to/reads_1.fastq.gz | samtools view -h -F 4 -b1 - > mapped_1.bam`

...and the same for the second end. Avoid multithreading with yara for now. Then call OT with the two bam files instead of fastq files.

**Comment by messersc** [comment]
RazerS3 3.5 is out and solved the problems we had with gzipped fastq's. But as @andras86 mentioned, swapping the first mapper for yara works perfectly fine.

**Comment by alvinwt** [comment]
Hi @andras86 and @messersc, 

I updated to RazerS3 3.5 and it is handling the gzipped files well. Just to check, does the prefiltering / alignment step for Optitype run in parallel? I'm not too familiar with the aligner but it doesn't do multiprocess for that step currently. Thanks both of you for your help!

**Comment by andras86** [comment]
Hi Alvin,

You can use the `-t` flag for Yara. Going above 4 doesn't seem to reduce wall-time too much but it does increase CPU time, so I'd choose something between 2-4.

**Comment by alvinwt** [comment]
Thanks @andras86, I'm  getting 
````
[bam_header_read] invalid BAM binary header (this is not a BAM file).
````

as the error message. 

The command I ran was 
````
yara_mapper -e 3 -f bam -u -t 4 -os hla_reference_dna 108T_JH_1.fastq.gz | samtools view -h -F 4 -b1 - > mapped_1.bam
````

Any clue how to get around this problem?

**Comment by andras86** [comment]
No idea, I just tried this very same command and it worked fine. You may have to take this to the Yara guys.
