### ISSUE TITLE
Create a version tag

### ISSUE THREAD

**Issue by rleonid** [FRED-2/OptiType#24]
We'd like to experiment with OptiType and I'd like to fix on a particular code set. Instead of relying on a commit, would it be possible to have a tagged version?

**Comment by datakid** [comment]
This is important for a number of reasons, reproducibility is a big one. 

Also, because it has a lot of dependencies, it makes it easier to then work out which dependencies are needed for which versions. 

I note that you use the phrase "OptiType uses the following software and libraries:". These are better framed as dependencies. Further, those dependencies should be listed not by version number *you* use, but by minimum version number required. 

Fore example: you cite HDF5 1.8.15.

Currently our cluster running SLURM, which we don't like to mess with too often, has HDF5 1.8.12 installed. This is the version available in the CentOS EPEL repositories.

1.8.15 is only available from the HDF5 website. 

Wouldn't normally be a problem except that SLURM has HDF5 as a dependency - so my only option is to turn off the cluster, uninstall slurm on the head, install new HDF5 packages, install new SLURM on head and all nodes. That's a lot of work and incredibly disruptive.

Luckily I'm in testing phase, so it's possible, if painful. 

With version numbers, I can at least look back to when HDF5 1.8.12 was an option and just have installed that.
