### ISSUE TITLE
Docker image reproducible and making biodocker the user is restrictive

### ISSUE THREAD

**Issue by mhalagan-nmdp** [FRED-2/OptiType#53]
The docker image can't be rebuilt locally because the source image *biodckr/biodocker* does not exist anymore. Also, making the *USER biodocker* means that a biodocker user needs to exist on whatever machine this container is being run on or the data and folders have to be read and writable by everyone.

**Comment by b-schubert** [comment]
The base image has been updated and the Dockerfile should be recompilable now (#54).

We chose BioDocker as base image and follow its guidelines because it is one of the largest Bioinformatics Docker projects. The use of biodocker as default user is a security measure and is recommended in the best practice guide of BioDocker.
