### ISSUE TITLE
What is the Objective value in the output

### ISSUE THREAD

**Issue by Rashesh7** [FRED-2/OptiType#89]
Hi,
I apologize if this is mentioned somewhere already, but what is the Objective value in the output. And how can it be used to qc the prediction?

Thanks,
Rashesh

**Comment by b-schubert** [comment]
The objective value is a regularized count of reads explained by the selected HLA genotype. 

QC is though since the objective function is the optimally achievable score. You could enumerate the solutions and create other (sub)-optimal solutions and compare their score and manually check the results in an alignment viewer of your choice.
