### ISSUE TITLE
Question about RazerS3 and "don't use the read mapper's paired-end capabilities".

### ISSUE THREAD

**Issue by NVSmirnova** [FRED-2/OptiType#92]
Could you explain me, why it is so important?

> Note: it's important that you filter the two ends individually. Don't use the read mapper's paired-end capabilities.

As I understand, this will distroy structure and logic of pair-end reads.

Thank you =)

**Comment by andras86** [comment]
Hi,

OptiType doesn't throw away paired-end information, it just handles them internally, instead of allowing the read mapper to do it. This way it isn't subject to the read mapper's pairing / filtering policies, and can rely on a more predictable input. As you can see in the coverage report pdf, OptiType does care about read pairs and distinguishes them from reads where only one end falls within the boundaries of the reference region.
