### ISSUE TITLE
How to output  the result with 8 digits ? 

### ISSUE THREAD

**Issue by lidd77** [FRED-2/OptiType#95]
HI,
 Whether Optitype supports the output of 8 digits ? 
I checked the paper ,but not found any information about it .

Thanks .

**Comment by b-schubert** [comment]
The direct output of Optitype is an HLA-ID corresponding to a fully specified HLA allele. 

Just return the results dataframe in line 416 of OptitypePipeline.py. 

**However, I would advise against using 8-digit results here since Optitype uses only exons 2 and 3 and thus is unable to resolve correctly 8-digit genotypes if the synonymous mutation does not lie within exons 2 and 3.**
